#!/usr/bin/env bash
#
# Copyright (c) 2024 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
pre_tf_build() {
    echo $PATH
    echo $USER
    echo $RUSTUP_HOME
    rustup default stable
    rustup target add --toolchain stable aarch64-unknown-none
    make -C "$tf_root/rust"
    make -C "$tf_root/rust" clippy
}
