#
# Copyright (c) 2025, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
#

source [file join [file dirname [info script]] utils.inc]
source [file join [file dirname [info script]] handle-arguments.inc]

expect {
    -re {Hit any key to stop autoboot:} {
        send "\r"
        send "boot\r"
    }
}

expect {
        "buildroot login:" {
                send "root\n"
        }
}

expect_string "#" "Linux Booted successfully"
