#
# Copyright (c) 2019-2024 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#
# Expect script for the test Secure Partition Cactus
#

source [file join [file dirname [info script]] handle-arguments.inc]

source [file join [file dirname [info script]] trusted-firmware.inc]

expect_string "Booting Secure Partition "

source [file join [file dirname [info script]] tftf.inc]

source [file join [file dirname [info script]] uart-hold.inc]
