#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_package() {
	use_debug_bins
}

test_setup() {
	set_hook_var "bin_mode" "debug"
}
