#!/usr/bin/env bash
#
# Copyright (c) 2024-2025, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job_template() {
	payload_type="linux" gen_yaml_template
}
generate_lava_job() {
	local model="base-aemv8a"

	uart="0" file="rfa.exp" track_expect
	# Track the rest of the UARTs to aid in debugging.
	uart="1" file="hold_uart.exp" track_expect
	uart="2" file="hold_uart.exp" track_expect
	uart="3" file="hold_uart.exp" track_expect

	model="$model" \
		has_ete="1" \
		amu_present="1" \
		has_mpam="1" \
		mpam_has_bw_ctrl="1" \
		has_trbe="1" \
		has_fgt2="1" \
		has_pmuv3p7="1" \
		memory_tagging_support_level="2" \
		has_branch_target_exception="1" \
		supports_trace_buffer_control_regs="1" \
		supports_trace_filter_regs="2" \
		supports_system_trace_filter_regs="1" \
		arch_version="9.0" \
		gen_model_params

	model="$model" gen_fvp_yaml
}
