#!/usr/bin/env bash
#
# Copyright (c) 2019-2020 Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

post_tf_build() {
	url="${optee_path}/tee-raw.bin" filename="bl32.bin" fetch_and_archive
}
