#!/usr/bin/env bash
#
# Copyright (c) 2024, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job_template() {
	payload_type="linux" gen_yaml_template
}
generate_lava_job() {
	local model="base-aemv8a"

	uart="0" file="tfa-next.exp" track_expect
	# Track the rest of the UARTs to aid in debugging.
	uart="1" file="hold_uart.exp" track_expect
	uart="2" file="hold_uart.exp" track_expect
	uart="3" file="hold_uart.exp" track_expect

	model="$model" gen_model_params

	model="$model" next_bin="1" gen_fvp_yaml
}
