#!/usr/bin/env bash
#
# Copyright (c) 2025, Arm Limited. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

generate_lava_job() {
	local model="cortex-x4"

	uart="0"

	model="$model" cache_state_modelled="0" gen_model_params
	model="$model" gen_fvp_yaml
}
