pipeline {
    agent {
        kubernetes {
            yamlFile 'tf-a-toolbox/.jenkins/pod.yaml'
            defaultContainer 'uv'
        }
    }

    options {
        timeout(time: 15, unit: 'MINUTES')
    }

    stages {
        stage('Validate') {
            steps {
                dir('tf-a-toolbox') {
                    sh 'uv sync --locked --dev --extra cli'

                    sh 'uv run ruff format --check .'
                    sh 'uv run ruff check .'

                    sh 'uv run ty check'
                    sh 'uv run pyright'

                    sh 'uv run pytest'
                }
            }
        }
    }

    post {
        always {
            script {
                if (!env.GERRIT_CHANGE_NUMBER) {
                    return
                }

                container('jnlp') {
                    withCredentials([sshUserPrivateKey(
                        credentialsId: 'TFA_CI_BOT_USER_SSH_KEY',
                        usernameVariable: 'USER',
                        keyFileVariable: 'KEY',
                    )]) {
                        def score = (currentBuild.currentResult == 'SUCCESS') ? 1 : -1

                        withEnv(["GERRIT_REVIEW_SCORE=${score}"]) {
                            sh '''
                                ssh -p 29418 -i "${KEY}" "${USER}@review.trustedfirmware.org" -o StrictHostKeyChecking=no \
                                    gerrit review --label "Verified-Toolbox=${GERRIT_REVIEW_SCORE}" "${GERRIT_PATCHSET_REVISION}"
                            '''
                        }
                    }
                }
            }
        }
    }
}
