#!/usr/bin/env bash
#
# Copyright (c) 2025-2026, Renesas Electronics Corporation. All rights reserved.
#
# SPDX-License-Identifier: BSD-3-Clause
#

pre_tf_build() {
	targets="bl2" set_tf_build_targets
}
